### ISSUE TITLE
Try out some collection traits

### ISSUE THREAD

**Issue by reem** [Gankro/collect-rs#107]

**Comment by apasel422** [comment]
I'm working on some map stuff for this, inspired by @Gankro's post [Replace Most of the Collections API with ranges and iterators](http://internals.rust-lang.org/t/crazy-replace-most-of-the-collections-api-with-ranges-and-iterators/1375).

**Comment by Gankro** [comment]
One issue with my proposal of having a Get/Remove/Insert traits is that the *semantics* for remove and insert are different for Maps and Sequences. Panic vs Option.

**Comment by apasel422** [comment]
See https://github.com/apasel422/eclectic.

This is very much a work in progress, and there are certain bugs with associated types that are preventing me from organizing this exactly the way I want. I opted to separate mutable functionality into separate traits, though there is an argument to be made for combining them.

I will be adding additional constraints for indexing and iteration (all three modes) in the future.

I also need to figure out a solution to the iterator discrepancy between maps like `TreeMap` and `TrieMap` (the former yields `(&K, &V)`, while the latter yields `(usize, &V)`). I have an idea for how to fix this using a `Borrow` bound on an associated `IterKey` type that would default to `&K` once we have default associated types, but the solution currently involves an extra lifetime parameter on `Map` that ends up propagating to all four map traits. I'll demonstrate this in another branch.

**Comment by apasel422** [comment]
https://github.com/rust-lang/rust/issues/20671 is also holding things up.
