### ISSUE TITLE
Consider including bitmap

### ISSUE THREAD

**Issue by Gankro** [Gankro/collect-rs#12]
https://github.com/cmr/rust-bitmap

cc @cmr

**Comment by cmr** [comment]
I'm hesitant to move `bitmap` here now, because I need it to work with just `core`.

**Comment by cmr** [comment]
Though I'm happy to just copy the implementation in and keep my fork

**Comment by Gankro** [comment]
That's cool, no worries. Was just blanket adding issues when I was setting this up.
