### ISSUE TITLE
Add Haskell-style traversables

### ISSUE THREAD

**Issue by alexchandel** [Gankro/collect-rs#132]
The Traversable type class is a pretty powerful abstraction in Haskell ([found here on Hackage](https://hackage.haskell.org/package/base-4.7.0.2/docs/Data-Traversable.html)). Rust already has a [fold](http://doc.rust-lang.org/std/iter/trait.IteratorExt.html#tymethod.fold) method for IteratorExt, which provides similar functionality to a `foldr`-based implementation of Traversable's parent, Foldable. But a `traverse()` method in IteratorExt could do much more!

Note that as far as I can tell (which may not be far :P), this "Traversable" is disjoint from the ["Traversable traits"](http://internals.rust-lang.org/t/traversable-traits/258) discussion, which (as far as I can tell) was more about working around the lack of HKTs vis-à-vis a trait for `.iter()` methods.

**Comment by reem** [comment]
Writing a trait equivalent to `Data.Traversable.Traversable` requires HKT for `Functor` and `Applicative`

**Comment by alexchandel** [comment]
@reem I imagine it can be done in a limited fashion without them, since we have a Foldable equivalent despite not having HKT for `Monoid`.

**Comment by reem** [comment]
`Monoid` does not require HKT.

```rust
pub trait Monoid {
      fn combine(self, Self) -> Self;
}
```

You can write HKT in Rust right now, it's just not pretty yet.
