### ISSUE TITLE
Clean up and enhance `TreeMap`

### ISSUE THREAD

**Issue by apasel422** [Gankro/collect-rs#137]
I've started work on a replacement at https://github.com/apasel422/tree.

**Comment by apasel422** [comment]
For what it's worth, I'd be happy to move my crate to `contain-rs` if it's deemed worthy, now or in the future.

**Comment by Gankro** [comment]
For now we should still migrate the old design, yeah?

**Comment by apasel422** [comment]
Sure. One problem is that my crate is using `tree` on crates.io, so I don't know how we'll publish it. (I probably shouldn't be using that identifier anyway.) It'd be nice if we could have a contain-rs namespace of some kind.

**Comment by Gankro** [comment]
CC @alexcrichton on namespaces

**Comment by Gankro** [comment]
Well we can leave it here for now and when yours gets big and strong migrate it.

**Comment by apasel422** [comment]
I can migrate the `collect::tree` to a `bst` crate under `contain-rs` if you approve that name.

**Comment by Gankro** [comment]
Works for me.
