### ISSUE TITLE
`TreeMap::insert`'s behavior differs from `{BTreeMap, HashMap}`

### ISSUE THREAD

**Issue by apasel422** [Gankro/collect-rs#144]
`{BTreeMap, HashMap}::insert` does not replace the existing key with the new one, but `TreeMap::insert` does. In common usage, this doesn't matter, as derived `{Hash, Eq}/Ord` impls incorporate all fields, but custom impls can experience surprising behavior despite meeting the requirements for `{Hash, Eq}/Ord`:
```rust
extern crate collect;

use std::cmp::Ordering;
use std::hash;

struct Foo(u32, &'static str);

impl hash::Hash for Foo {
    fn hash<H: hash::Hasher>(&self, h: &mut H) { self.0.hash(h); }
}

impl PartialEq for Foo {
    fn eq(&self, other: &Foo) -> bool { self.0 == other.0 }
}

impl Eq for Foo {}

impl PartialOrd for Foo {
    fn partial_cmp(&self, other: &Foo) -> Option<Ordering> { Some(self.cmp(other)) }
}

impl Ord for Foo {
    fn cmp(&self, other: &Foo) -> Ordering { self.0.cmp(&other.0) }
}

#[test]
fn test_tree_map() {
    use collect::TreeMap;

    let mut m = TreeMap::new();

    m.insert(Foo(1, "a"), ());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_some());

    m.insert(Foo(1, "b"), ());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_none());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "b").is_some());
}

#[test]
fn test_btree_map() {
    use std::collections::BTreeMap;

    let mut m = BTreeMap::new();

    m.insert(Foo(1, "a"), ());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_some());

    m.insert(Foo(1, "b"), ());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_none());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "b").is_some());
}

#[test]
fn test_hash_map() {
    use std::collections::HashMap;

    let mut m = HashMap::new();

    m.insert(Foo(1, "a"), ());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_some());

    m.insert(Foo(1, "b"), ());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_none());
    assert!(m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "b").is_some());
}
```
```
running 3 tests
test test_btree_map ... FAILED
test test_hash_map ... FAILED
test test_tree_map ... ok

failures:

---- test_btree_map stdout ----
	thread 'test_btree_map' panicked at 'assertion failed: m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_none()', src/lib.rs:50


---- test_hash_map stdout ----
	thread 'test_hash_map' panicked at 'assertion failed: m.iter().find(|&(k, _)| k.0 == 1 && k.1 == "a").is_none()', src/lib.rs:64
```
The fix for `collect` is simple (remove [this line](https://github.com/Gankro/collect-rs/blob/master/src/tree/map.rs#L1198)), but I'm not sure if this should be considered a bug in `std`. In either case, the behavior should be the same.

**Comment by Gankro** [comment]
My general opinion on this has been to leave it unspecified, since the collections don't even acknowledge that you *could* care. Not swapping the keys is faster, but swapping the keys might be more useful.

**Comment by apasel422** [comment]
Individual map types can specify the behavior (or leave it unspecified),
but I do think it should be documented. There's also the problem of how the
entry method interacts with this. It would be surprising for the two to
differ.

**Comment by Gankro** [comment]
I'm 99.9% certain that I made sure that the Entry APIs match up.

**Comment by apasel422** [comment]
Yeah, they do match for BTreeMap and HashMap. TreeMap doesn't have the
entry API, but if it is added (my tree crate maintains the current
behavior), insert will likely differ and need to be updated.

**Comment by Gankro** [comment]
Unless you have a concrete usecase for changing the key, I'd be fine with just specifying that it remains the same, to avoid the cost of replacing it.
