### ISSUE TITLE
Something Something Intrusive Collections Something Something?

### ISSUE THREAD

**Issue by Gankro** [Gankro/collect-rs#25]
I have no idea but apparently it's a thing that people do?

**Comment by Ericson2314** [comment]
https://github.com/RustOS-Fork-Holding-Ground/intrusive-red-black-tree generic, intrusive, no macros!

**Comment by Ericson2314** [comment]
Are you closing this to postpone it? Just curious.

**Comment by Gankro** [comment]
@Ericson2314 The project is being split up into many different crates at github.com/contain-rs (see #138 ). Just closing all issues. Not clear where the best place to have this discussion is now. Maybe github.com/contain-rs/admin?

**Comment by Ericson2314** [comment]
Oh cool! Yeah I guess that would be a good spot for them.
