### ISSUE TITLE
Consolidate map and set tests

### ISSUE THREAD

**Issue by apasel422** [Gankro/collect-rs#81]
It would be nice to have a module containing tests for the behavior that is common to all map and set implementations. @Gankro started something similar with https://github.com/Gankro/rust-collection-tests, but it needs to be updated for various changes to the language and libraries, including the removal of the collection traits. For now, this could use macros.

**Comment by apasel422** [comment]
It could also contain quickcheck tests.

**Comment by reem** [comment]
Automatic test generation using macros + quickcheck would be amazing, major +1
