### ISSUE TITLE
Reintroduce collection traits

### ISSUE THREAD

**Issue by apasel422** [Gankro/collect-rs#82]
In their most general form, these may require features that haven't been added to Rust yet, but we can probably start thinking about what they would look like.

**Comment by Gankro** [comment]
I started a thread about exactly this this morning: http://discuss.rust-lang.org/t/collection-traits-take-2/1272

**Comment by reem** [comment]
@sfackler's concern about bounding Q is extremely important. Haskell has had this problem for eons and it was only solved with much more advanced stuff like ConstraintKinds.

**Comment by apasel422** [comment]
Closing in favor of #107.
