### ISSUE TITLE
version was not bumped on crates.io?

### ISSUE THREAD

**Issue by pfalabella** [Gankro/collect-rs#89]
I can't compile the version from crates.io, but can compile the one from git.

**Comment by apasel422** [comment]
Which version of `rustc` are you using?

**Comment by reem** [comment]
Just pushed a new version to crates.io, does that fix it?

**Comment by pfalabella** [comment]
@reem yes, it does. Thanks!

@apasel422 
````
rustc 1.0.0-nightly (4bed1e8c0 2015-01-12 00:21:32 +0000)
binary: rustc
commit-hash: 4bed1e8c0a433f30f85a01cd74d2251c73f590a2
commit-date: 2015-01-12 00:21:32 +0000
host: x86_64-pc-windows-gnu
release: 1.0.0-nightly
````

**Comment by Gankro** [comment]
@reem thanks! (also I just now fixed my install -- the problem was that I'm a moron)
