### ISSUE TITLE
Check out cool no-unsafe-code intrusive-style dlist

### ISSUE THREAD

**Issue by reem** [Gankro/collect-rs#95]
@pythonesque showed this to me on IRC: https://gist.github.com/pythonesque/5943252fb464b49123fa#file-dlist-rs

It's a fascinating approach to implementing a DList that requires no unsafe code - instead of having an overarching handle to the head and tail, you instead access one node at a time, similar to a cursor or zipper over the structure, and it then safely patches itself up as you move around.

This seems like a killer justification for the use of Zippers/Cursors and/or Traversals and is also really darn cool.

**Comment by Gankro** [comment]
It's a cool idea, but iteration required mutation, which seems like a Rust non-starter.

**Comment by pythonesque** [comment]
@Gankro I see it being useful in some contexts but it will always be a specialized solution.

**Comment by Gankro** [comment]
Definitely logging it in my design bank though, if only as a funner answer to "how do I implement a doubly linked list in Rust?"
