### ISSUE TITLE
Some types are missing `Debug` impls

### ISSUE THREAD

**Issue by apasel422** [Gankro/collect-rs#98]
The following collections are missing a `std::fmt::Debug` impl:
- [x] `interval_heap::IntervalHeap` (I have an upcoming PR for this)
- [x] `proto::linear_map::LinearMap`
- [ ] `proto::par_vec::ParVec`

The following types are missing a `Debug` impl, but it is not clear whether they should have one or what the output should be. One possibility is just the name of the struct or enum variant.
- [ ] `immut_slist::Iter`
- [ ] `proto::linear_map::Iter`
- [ ] `proto::linear_map::IterMut`
- [ ] `proto::linear_map::Keys`
- [ ] `proto::linear_map::Values`
- [ ] `tree_map::IntoIter`
- [ ] `tree_map::Iter`
- [ ] `tree_map::IterMut`
- [ ] `tree_map::Keys`
- [ ] `tree_map::RevIter`
- [ ] `tree_map::RevIterMut`
- [ ] `tree_map::Values`
- [ ] `tree_set::Difference`
- [ ] `tree_set::Intersection`
- [ ] `tree_set::IntoIter`
- [ ] `tree_set::Iter`
- [ ] `tree_set::RevIter`
- [ ] `tree_set::SymmetricDifference`
- [ ] `tree_set::Union`

**Comment by tbu-** [comment]
How did you generate this?

**Comment by apasel422** [comment]
@tbu- By looking at Rustdoc manually.

**Comment by apasel422** [comment]
See https://github.com/rust-lang/rust/issues/20855.
