### ISSUE TITLE
Be consistent with `Keys` and `Values` iterators

### ISSUE THREAD

**Issue by apasel422** [Gankro/collect-rs#99]
`tree_map` uses a wrapper struct for its `Keys` and `Values` iterators, but `trie_map` does not.

**Comment by reem** [comment]
I believe the current (IMO annoying :P) convention is to use newtypes.

**Comment by Gankro** [comment]
@aturon has plans for some kind of macro to make this more ergonomic.

But yeah, annoying.

**Comment by Gankro** [comment]
Strictly speaking *we* could not bother since we make no back-compat guarantees at all.

**Comment by aturon** [comment]
@Gankro I believe a few such macros are currently in use in `std` for this purpose.

**Comment by aturon** [comment]
(I think it'd be interesting to try to provide a robust form of these macros in crates.io, but I won't have time to do that myself any time soon.)

**Comment by apasel422** [comment]
Is there even a reason to have these iterators? Adaptors provide the same functionality without the combinatoric explosion of key-value/mutable-immutable/forward-reverse/subrange variants.

**Comment by Gankro** [comment]
Hmm... I... Don't disagree.

**Comment by tbu-** [comment]
You're making the intent clearer if you ask for keys or values only – also there's the possibility of implementing "just getting the keys" in a more efficient way, because it doesn't have to touch the values.

**Comment by reem** [comment]
Ideally there's a way to get a keys iterator that doesn't contain the values type - this has been a problem for me in the past.

Thanks,
         Jonathan Reem

**Comment by apasel422** [comment]
@reem As written, both forms (type alias and wrapper struct) reference the value type. Without being space-inefficient or using trait objects or unsafe code, I don't see how they can be written without being parameterized over the value.

**Comment by reem** [comment]
Depending on the data structure it is sometimes possible to do it unsafely.

Thanks,
         Jonathan Reem

**Comment by apasel422** [comment]
Closing because `trie` is now in an external crate. CC contain-rs/trie#4.
